### ISSUE TITLE
Problem of installing the blosc filter plugin for hdf5

### ISSUE THREAD

**Issue by Ethan-Zhou** [tub-rip/events_h52bag#3] opened 2021-10-18 12:01 UTC
Hi,
I come across a problem when installing the blosc filter plugin for hdf5. Specifically, it failed to fetch blosc, as seen attached.
![make_failure](https://user-images.githubusercontent.com/5391344/137725749-cf02fde0-0c19-44c4-80c7-679820cecb44.png)
Since I have no problem to git clone from blosc repository. I would like to know if you can solve this problem to make users' life easier.
Cheers,
yi

**Comment by ghoshsuman** [comment] 2021-10-18 19:00
Hi @Ethan-Zhou I couldn't reproduce this error but I guess it has something to do with https access to the c-blosc repository. Can you try using SSH instead of HTTPS by editing the repo link to `git@github.com:Blosc/c-blosc.git` in [this line](https://github.com/Blosc/hdf5-blosc/blob/bd8ee59708f366ac561153858735165d3a543b18/CMakeLists.txt#L27)?

**Comment by Ethan-Zhou** [comment] 2021-10-20 00:08
Hi @ghoshsuman , the SSH one fixed the problem.
Then I come across another problem. I do not have **/plugin**  directory under my hdf5-dev installation. 

Below is what `dpkg -L libhdf5-dev` returns

```
/usr/include/hdf5
/usr/include/hdf5/serial
/usr/include/hdf5/serial/H5ACpublic.h
/usr/include/hdf5/serial/H5AbstractDs.h
/usr/include/hdf5/serial/H5Apublic.h
/usr/include/hdf5/serial/H5ArrayType.h
/usr/include/hdf5/serial/H5AtomType.h
/usr/include/hdf5/serial/H5Attribute.h
/usr/include/hdf5/serial/H5Classes.h
/usr/include/hdf5/serial/H5CommonFG.h
/usr/include/hdf5/serial/H5CompType.h
/usr/include/hdf5/serial/H5Cpp.h
/usr/include/hdf5/serial/H5CppDoc.h
/usr/include/hdf5/serial/H5Cpublic.h
/usr/include/hdf5/serial/H5DOpublic.h
/usr/include/hdf5/serial/H5DSpublic.h
/usr/include/hdf5/serial/H5DataSet.h
/usr/include/hdf5/serial/H5DataSpace.h
/usr/include/hdf5/serial/H5DataType.h
/usr/include/hdf5/serial/H5DcreatProp.h
/usr/include/hdf5/serial/H5Dpublic.h
/usr/include/hdf5/serial/H5DxferProp.h
/usr/include/hdf5/serial/H5EnumType.h
/usr/include/hdf5/serial/H5Epubgen.h
/usr/include/hdf5/serial/H5Epublic.h
/usr/include/hdf5/serial/H5Exception.h
/usr/include/hdf5/serial/H5FDcore.h
/usr/include/hdf5/serial/H5FDdirect.h
/usr/include/hdf5/serial/H5FDfamily.h
/usr/include/hdf5/serial/H5FDlog.h
/usr/include/hdf5/serial/H5FDmpi.h
/usr/include/hdf5/serial/H5FDmpio.h
/usr/include/hdf5/serial/H5FDmulti.h
/usr/include/hdf5/serial/H5FDpublic.h
/usr/include/hdf5/serial/H5FDsec2.h
/usr/include/hdf5/serial/H5FDstdio.h
/usr/include/hdf5/serial/H5FaccProp.h
/usr/include/hdf5/serial/H5FcreatProp.h
/usr/include/hdf5/serial/H5File.h
/usr/include/hdf5/serial/H5FloatType.h
/usr/include/hdf5/serial/H5Fpublic.h
/usr/include/hdf5/serial/H5Gpublic.h
/usr/include/hdf5/serial/H5Group.h
/usr/include/hdf5/serial/H5IMpublic.h
/usr/include/hdf5/serial/H5IdComponent.h
/usr/include/hdf5/serial/H5Include.h
/usr/include/hdf5/serial/H5IntType.h
/usr/include/hdf5/serial/H5Ipublic.h
/usr/include/hdf5/serial/H5LDpublic.h
/usr/include/hdf5/serial/H5LTpublic.h
/usr/include/hdf5/serial/H5Library.h
/usr/include/hdf5/serial/H5Location.h
/usr/include/hdf5/serial/H5Lpublic.h
/usr/include/hdf5/serial/H5MMpublic.h
/usr/include/hdf5/serial/H5Object.h
/usr/include/hdf5/serial/H5OcreatProp.h
/usr/include/hdf5/serial/H5Opublic.h
/usr/include/hdf5/serial/H5PLextern.h
/usr/include/hdf5/serial/H5PLpublic.h
/usr/include/hdf5/serial/H5PTpublic.h
/usr/include/hdf5/serial/H5PacketTable.h
/usr/include/hdf5/serial/H5Ppublic.h
/usr/include/hdf5/serial/H5PredType.h
/usr/include/hdf5/serial/H5PropList.h
/usr/include/hdf5/serial/H5Rpublic.h
/usr/include/hdf5/serial/H5Spublic.h
/usr/include/hdf5/serial/H5StrType.h
/usr/include/hdf5/serial/H5TBpublic.h
/usr/include/hdf5/serial/H5Tpublic.h
/usr/include/hdf5/serial/H5VarLenType.h
/usr/include/hdf5/serial/H5Zpublic.h
/usr/include/hdf5/serial/H5api_adpt.h
/usr/include/hdf5/serial/H5f90i.h
/usr/include/hdf5/serial/H5f90i_gen.h
/usr/include/hdf5/serial/H5overflow.h
/usr/include/hdf5/serial/H5pubconf.h
/usr/include/hdf5/serial/H5public.h
/usr/include/hdf5/serial/H5version.h
/usr/include/hdf5/serial/h5_gen.mod
/usr/include/hdf5/serial/h5a.mod
/usr/include/hdf5/serial/h5d.mod
/usr/include/hdf5/serial/h5ds.mod
/usr/include/hdf5/serial/h5e.mod
/usr/include/hdf5/serial/h5f.mod
/usr/include/hdf5/serial/h5fortkit.mod
/usr/include/hdf5/serial/h5fortran_types.mod
/usr/include/hdf5/serial/h5g.mod
/usr/include/hdf5/serial/h5global.mod
/usr/include/hdf5/serial/h5i.mod
/usr/include/hdf5/serial/h5im.mod
/usr/include/hdf5/serial/h5l.mod
/usr/include/hdf5/serial/h5lib.mod
/usr/include/hdf5/serial/h5lt.mod
/usr/include/hdf5/serial/h5lt_const.mod
/usr/include/hdf5/serial/h5o.mod
/usr/include/hdf5/serial/h5p.mod
/usr/include/hdf5/serial/h5r.mod
/usr/include/hdf5/serial/h5s.mod
/usr/include/hdf5/serial/h5t.mod
/usr/include/hdf5/serial/h5tb.mod
/usr/include/hdf5/serial/h5tb_const.mod
/usr/include/hdf5/serial/h5z.mod
/usr/include/hdf5/serial/hdf5.h
/usr/include/hdf5/serial/hdf5.mod
/usr/include/hdf5/serial/hdf5_hl.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/hdf5
/usr/lib/x86_64-linux-gnu/hdf5/serial
/usr/lib/x86_64-linux-gnu/libhdf5_cpp.a
/usr/lib/x86_64-linux-gnu/libhdf5_hl_cpp.a
/usr/lib/x86_64-linux-gnu/libhdf5_serial.a
/usr/lib/x86_64-linux-gnu/libhdf5_serial.settings
/usr/lib/x86_64-linux-gnu/libhdf5_serial_fortran.a
/usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.a
/usr/lib/x86_64-linux-gnu/libhdf5_serialhl_fortran.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/hdf5-serial.pc
/usr/share
/usr/share/doc
/usr/share/doc/libhdf5-dev
/usr/share/doc/libhdf5-dev/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/libhdf5-dev
/usr/lib/x86_64-linux-gnu/hdf5/serial/include
/usr/lib/x86_64-linux-gnu/hdf5/serial/lib
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.a
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.settings
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.a
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_fortran.a
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_fortran.so
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.a
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.so
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl_cpp.a
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl_cpp.so
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5hl_fortran.a
/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5hl_fortran.so
/usr/lib/x86_64-linux-gnu/libhdf5_cpp.so
/usr/lib/x86_64-linux-gnu/libhdf5_hl_cpp.so
/usr/lib/x86_64-linux-gnu/libhdf5_serial.so
/usr/lib/x86_64-linux-gnu/libhdf5_serial_fortran.so
/usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so
/usr/lib/x86_64-linux-gnu/libhdf5_serialhl_fortran.so
```

**Comment by ghoshsuman** [comment] 2021-10-20 11:16
You need to create the `plugins` directory inside `/usr/lib/x86_64-linux-gnu/hdf5/` and paste the library file inside.

**Comment by ghoshsuman** [comment] 2021-11-16 23:45
Hi @Ethan-Zhou if you managed to install it, could you please close the issue?

**Closed as completed** 2021-12-03 02:44 UTC
